import { readFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { loadConfig } from "../config/loader.js";
import { parsePolarisIgnore } from "../ignore/parser.js";
import { SECRET_PATTERNS } from "../ignore/defaults.js";
import { inferRoute } from "./inference.js";
import {
  detectOperationalReasons,
  isCognitionSkippedFolder,
  isPolarisOwnedFolder,
} from "../cognition/index.js";
import {
  readFileRoutes,
  readNeedsReview,
  readExemptions,
  writeFileRoutes,
  writeNeedsReview,
  writeAtlasIndex,
  resolveInstructionFile,
  computeInstructionCoverage,
  type FileRouteEntry,
} from "./atlas.js";

const SECRET_REGEXES = SECRET_PATTERNS.map(
  (p) => new RegExp("^" + p.replace(/\./g, "\\.").replace(/\*/g, ".*") + "$"),
);

function isSecretFile(filePath: string): boolean {
  const parts = filePath.split("/");
  const base = parts[parts.length - 1]!;
  return SECRET_REGEXES.some((re) => re.test(base) || re.test(filePath));
}

function getChangedFiles(repoRoot: string, fromCommit?: string, toCommit?: string): string[] {
  const from = fromCommit ?? "HEAD~1";
  const to = toCommit ?? "HEAD";
  try {
    const output = execFileSync("git", ["diff", "--name-only", `${from}..${to}`], {
      cwd: repoRoot,
      stdio: ["pipe", "pipe", "pipe"],
    }).toString().trim();
    if (!output) return [];
    return output.split("\n").map((f) => f.trim()).filter(Boolean);
  } catch {
    // Fall back to unstaged changes if no commits
    try {
      const output = execFileSync("git", ["diff", "--name-only"], {
        cwd: repoRoot,
        stdio: ["pipe", "pipe", "pipe"],
      }).toString().trim();
      if (!output) return [];
      return output.split("\n").map((f) => f.trim()).filter(Boolean);
    } catch {
      return [];
    }
  }
}

function loadIgnoreFilter(repoRoot: string): ReturnType<typeof parsePolarisIgnore> {
  let userPatterns: string[] = [];
  try {
    const raw = readFileSync(resolve(repoRoot, ".polarisignore"), "utf-8");
    userPatterns = raw.split(/\r?\n/).filter((line) => line.trim() !== "" && !line.startsWith("#"));
  } catch (err) {
    if (typeof err === "object" && err !== null && "code" in err && (err as { code: string }).code !== "ENOENT") {
      throw err;
    }
  }
  return parsePolarisIgnore(userPatterns);
}

export interface UpdateSummary {
  mapped: number;
  validated: number;
  inferred: number;
  needs_review: number;
  ignored: number;
  /** Folders missing POLARIS.md that are newly eligible. */
  missing_polaris?: string[];
  /** Folders missing SUMMARY.md that have a POLARIS.md (eligible for one). */
  missing_summary?: string[];
  /** Folders that were seeded with draft cognition files (only when --seed-cognition). */
  seeded?: string[];
}

/**
 * Draft POLARIS.md content for a newly discovered eligible folder.
 */
function draftPolarismd(folderRel: string): string {
  return [
    `# ${folderRel}`,
    "",
    "<!-- DRAFT: Generated by polaris map update --seed-cognition -->",
    "<!-- Fill in all sections before committing. Do not leave TODOs in production. -->",
    "",
    "## Purpose",
    "",
    "<!-- TODO -->",
    "",
    "## What belongs here",
    "",
    "<!-- TODO -->",
    "",
    "## What does not belong here",
    "",
    "<!-- TODO -->",
    "",
    "## Editing rules",
    "",
    "<!-- TODO -->",
    "",
    "## Related routes",
    "",
    "<!-- TODO -->",
    "",
  ].join("\n");
}

/**
 * Draft SUMMARY.md content for a newly discovered eligible folder.
 */
function draftSummarymd(folderRel: string): string {
  return [
    `# ${folderRel} — Summary`,
    "",
    "<!-- DRAFT: Generated by polaris map update --seed-cognition -->",
    "<!-- TODO: Short informational summary of this route. Keep under 4 KB. -->",
    "<!-- Informational only. Do not add operational doctrine here. -->",
    "",
  ].join("\n");
}

/**
 * Detect folders touched by changed files that are missing POLARIS.md or
 * SUMMARY.md. Only eligible non-skipped folders are reported.
 * Root is skipped unless includeRoot=true.
 */
export function detectMissingCognitionSurfaces(
  changedFiles: string[],
  repoRoot: string,
  includeRoot?: boolean,
): { missingPolaris: string[]; missingSummary: string[] } {
  const missingPolaris = new Set<string>();
  const missingSummary = new Set<string>();
  const tierOneFolders = new Set<string>([".polaris", "src", "smartdocs/specs/active"]);

  if (existsSync(resolve(repoRoot, "smartdocs", "doctrine", "active"))) {
    tierOneFolders.add("smartdocs/doctrine/active");
  }
  if (existsSync(resolve(repoRoot, "src"))) {
    for (const entry of readdirSync(resolve(repoRoot, "src"), { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      tierOneFolders.add(`src/${entry.name}`);
    }
  }

  const hasNonTestNonGeneratedSource = (filePath: string): boolean => {
    const normalized = filePath.replace(/\\/g, "/");
    const fileName = normalized.split("/").pop() ?? normalized;
    if (
      normalized.startsWith(".") ||
      /(^|\/)(dist|build|out|coverage|generated|__generated__)\//.test(normalized) ||
      /(^|\/)\.(?!well-known)/.test(normalized)
    ) return false;
    if (
      /\.test\./.test(fileName) ||
      /\.spec\./.test(fileName) ||
      /\.generated\./.test(fileName) ||
      fileName.endsWith(".d.ts")
    ) return false;
    return /\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|kt|swift|rb|php|cs|c|cc|cpp|h|hpp|sh)$/.test(fileName);
  };

  const detectFolderForFile = (filePath: string): string | null => {
    const parts = filePath.split("/");
    for (let i = parts.length - 1; i >= 1; i--) {
      const dir = parts.slice(0, i).join("/");
      if (!dir || isCognitionSkippedFolder(dir, repoRoot)) continue;

      if (isPolarisOwnedFolder(dir)) return dir;

      const folderTouchedFiles = changedFiles.filter((changed) => changed.startsWith(`${dir}/`));
      const sourceTouchedFiles = folderTouchedFiles.filter(hasNonTestNonGeneratedSource);
      if (sourceTouchedFiles.length === 0) continue;
      if (detectOperationalReasons(sourceTouchedFiles).length === 0) continue;
      return dir;
    }
    return null;
  };

  for (const tierOne of tierOneFolders) {
    if (!existsSync(resolve(repoRoot, tierOne))) continue;
    if (isCognitionSkippedFolder(tierOne, repoRoot)) continue;

    const hasPolarismd = existsSync(resolve(repoRoot, tierOne, "POLARIS.md"));
    const hasSummarymd = existsSync(resolve(repoRoot, tierOne, "SUMMARY.md"));
    if (!hasPolarismd) missingPolaris.add(tierOne);
    if (hasPolarismd && !hasSummarymd) missingSummary.add(tierOne);
  }

  for (const file of changedFiles) {
    const folder = detectFolderForFile(file);
    const foundAncestor = Boolean(folder);
    if (folder) {
      const hasPolarismd = existsSync(resolve(repoRoot, folder, "POLARIS.md"));
      const hasSummarymd = existsSync(resolve(repoRoot, folder, "SUMMARY.md"));
      if (!hasPolarismd) missingPolaris.add(folder);
      if (hasPolarismd && !hasSummarymd) missingSummary.add(folder);
    }
    // Check root only when explicitly opted in and no non-root ancestor was found
    if (includeRoot && !foundAncestor) {
      const hasPolarismd = existsSync(resolve(repoRoot, "POLARIS.md"));
      const hasSummarymd = existsSync(resolve(repoRoot, "SUMMARY.md"));
      if (!hasPolarismd) missingPolaris.add("");
      if (hasPolarismd && !hasSummarymd) missingSummary.add("");
    }
  }

  return {
    missingPolaris: Array.from(missingPolaris),
    missingSummary: Array.from(missingSummary),
  };
}

/**
 * Seed draft POLARIS.md and/or SUMMARY.md files for newly eligible folders.
 * Only called when --seed-cognition flag is explicitly set.
 * Root is skipped unless includeRoot=true. Already-existing files are never overwritten.
 *
 * Returns the list of folders that were actually seeded.
 */
export function seedCognitionDrafts(
  folders: { polaris: string[]; summary: string[] },
  repoRoot: string,
  includeRoot?: boolean,
): string[] {
  const seeded: string[] = [];

  for (const dir of folders.polaris) {
    // Root (empty string) is only seeded when explicitly opted in
    if (!includeRoot && !dir) continue;
    if (dir && isCognitionSkippedFolder(dir, repoRoot)) continue;
    const target = dir ? resolve(repoRoot, dir, "POLARIS.md") : resolve(repoRoot, "POLARIS.md");
    if (!existsSync(target)) {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, draftPolarismd(dir || "."), "utf-8");
      seeded.push(dir ? `${dir}/POLARIS.md` : "POLARIS.md");
    }
  }

  for (const dir of folders.summary) {
    if (!includeRoot && !dir) continue;
    if (dir && isCognitionSkippedFolder(dir, repoRoot)) continue;
    const target = dir ? resolve(repoRoot, dir, "SUMMARY.md") : resolve(repoRoot, "SUMMARY.md");
    if (!existsSync(target)) {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, draftSummarymd(dir || "."), "utf-8");
      seeded.push(dir ? `${dir}/SUMMARY.md` : "SUMMARY.md");
    }
  }

  return seeded;
}

export function runMapUpdate(
  repoRoot: string,
  explicitFiles: string[],
  fromCommit?: string,
  toCommit?: string,
  seedCognition?: boolean,
  includeRoot?: boolean,
): { summary: UpdateSummary; hasNeedsReview: boolean } {
  const config = loadConfig(repoRoot);
  const outputPath = resolve(repoRoot, config.repo.sidecarOutputPath ?? ".polaris/map");
  const ig = loadIgnoreFilter(repoRoot);

  const changedFiles = explicitFiles.length > 0
    ? explicitFiles
    : getChangedFiles(repoRoot, fromCommit, toCommit);

  const routes = readFileRoutes(outputPath);
  const needsReview = readNeedsReview(outputPath);
  const exemptions = readExemptions(outputPath);

  let branchName = "";
  try {
    branchName = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
      cwd: repoRoot,
      stdio: ["pipe", "pipe", "pipe"],
    }).toString().trim();
  } catch { /* ignore */ }

  const summary: UpdateSummary = { mapped: 0, validated: 0, inferred: 0, needs_review: 0, ignored: 0 };
  const now = new Date().toISOString();

  for (const filePath of changedFiles) {
    // Security check
    if (isSecretFile(filePath)) {
      console.error(`[HIGH] Secret file pattern matched, skipping: ${filePath}`);
      summary.ignored++;
      continue;
    }

    // 1. .polarisignore
    if (ig.ignores(filePath)) {
      summary.ignored++;
      continue;
    }

    // 2. File doesn't exist on disk (deleted) → remove from both indexes, skip
    if (!existsSync(resolve(repoRoot, filePath))) {
      delete needsReview[filePath];
      delete routes[filePath];
      summary.ignored++;
      continue;
    }

    // 3. Existing entry in file-routes.json → validate and update timestamp
    if (routes[filePath]) {
      routes[filePath]!.last_updated = now;
      routes[filePath]!.updated_by = "polaris-map-update";
      routes[filePath]!.instructionFile = resolveInstructionFile(filePath, repoRoot);
      summary.validated++;
      continue;
    }

    // 4. Tracked-not-indexed → skip
    if (exemptions[filePath]) {
      summary.ignored++;
      continue;
    }

    // 5. Run inference for new file
    const inferred = inferRoute(filePath, repoRoot, config, routes, branchName);
    const autoWriteAbove = config.map.autoWriteAbove ?? 0.85;
    const confidenceThreshold = config.map.confidenceThreshold ?? 0.75;
    const entry: FileRouteEntry = {
      domain: inferred.domain,
      route: inferred.route,
      taskchain: inferred.taskchain,
      confidence: inferred.confidence,
      classification: inferred.confidence >= autoWriteAbove ? "indexed" : "needs-review",
      last_updated: now,
      updated_by: "polaris-map-update",
      tags: inferred.tags,
      instructionFile: resolveInstructionFile(filePath, repoRoot),
    };

    if (inferred.confidence >= autoWriteAbove) {
      routes[filePath] = entry;
      delete needsReview[filePath];
      summary.inferred++;
      summary.mapped++;
    } else {
      needsReview[filePath] = entry;
      delete routes[filePath];
      summary.needs_review++;
      if (inferred.confidence >= confidenceThreshold) {
        // Between thresholds: also track in needs-review but don't fail by default
      } else {
        const onLow = config.map.onLowConfidence ?? "warn";
        if (onLow === "warn") {
          console.error(`[WARN] Low confidence (${inferred.confidence.toFixed(2)}) for ${filePath} — added to needs-review`);
        }
      }
    }
  }

  writeFileRoutes(outputPath, routes);
  writeNeedsReview(outputPath, needsReview);

  const allEntries = { ...routes, ...needsReview };
  const totalFiles = Object.keys(allEntries).length;
  const indexedCount = Object.values(allEntries).filter((e) => e.classification === "indexed").length;
  writeAtlasIndex(outputPath, {
    scan_date: now,
    file_count: totalFiles,
    coverage_pct: totalFiles > 0 ? Math.round((indexedCount / totalFiles) * 100) : 0,
    instructionCoverage: computeInstructionCoverage(allEntries),
    entries: allEntries,
  });

  // ── Cognition surface detection ─────────────────────────────────────────
  // Detect newly eligible folders missing POLARIS.md or SUMMARY.md.
  // Default: report only. With seedCognition=true: create draft files.
  // Root is skipped by default; opt in with includeRoot=true.
  // Agent/generated/runtime folders are always skipped.
  const { missingPolaris, missingSummary } = detectMissingCognitionSurfaces(
    changedFiles,
    repoRoot,
    includeRoot,
  );

  summary.missing_polaris = missingPolaris;
  summary.missing_summary = missingSummary;

  if (missingPolaris.length > 0) {
    console.error(`[INFO] Folders missing POLARIS.md (${missingPolaris.length}): ${missingPolaris.join(", ")}`);
  }
  if (missingSummary.length > 0) {
    console.error(`[INFO] Folders eligible for SUMMARY.md (${missingSummary.length}): ${missingSummary.join(", ")}`);
  }

  if (seedCognition) {
    const seeded = seedCognitionDrafts(
      { polaris: missingPolaris, summary: missingSummary },
      repoRoot,
      includeRoot,
    );
    summary.seeded = seeded;
    if (seeded.length > 0) {
      console.error(`[INFO] Seeded draft cognition files (${seeded.length}): ${seeded.join(", ")}`);
    }
  }

  console.log(JSON.stringify(summary));
  return { summary, hasNeedsReview: summary.needs_review > 0 };
}
