import { execFileSync } from "node:child_process";
import { resolveTelemetryFilePath } from "../loop/continue.js";
import { readJsonLines } from "../autoresearch/gates.js";
import {
  summarizeRouterOutcomes,
  type RouterOutcomesSummary,
  type RunArtifacts,
} from "../autoresearch/score.js";
import type { LoopState, ProviderRoutingSummary } from "../loop/checkpoint.js";

export interface CreatePrOptions {
  repoRoot: string;
  branch: string;
  state: LoopState;
  draft: boolean;
  /** When provided, overrides state.completed_children.length in PR body. */
  authoritativeChildCount?: number;
  /** Optional provider routing summary for the PR body. */
  routingSummary?: ProviderRoutingSummary;
  /** Optional router outcome summary for the PR body. */
  routerOutcomes?: RouterOutcomesSummary;
}

function inferRoutingMode(summary: ProviderRoutingSummary): string {
  if (typeof summary.compatibility_mode === "boolean") {
    return summary.compatibility_mode ? "compatibility" : "router";
  }
  return "—";
}

function renderRoutingReview(outcomes: RouterOutcomesSummary): string {
  const lines: string[] = [];

  if (outcomes.recurring_failures.length > 0) {
    lines.push("- Recurring router failures:");
    for (const f of outcomes.recurring_failures) {
      lines.push(
        `  - ${f.reason}: ${f.occurrences} occurrence(s) — children: ${f.child_ids.join(", ") || "none"}`,
      );
    }
  }

  if (outcomes.provider_monopoly_signals.length > 0) {
    lines.push("- Provider monopoly (repeated same-provider selection):");
    for (const s of outcomes.provider_monopoly_signals) {
      lines.push(
        `  - ${s.reason}: ${s.occurrences} occurrence(s) — children: ${s.child_ids.join(", ") || "none"}`,
      );
    }
  }

  if (outcomes.evidence_gap_signals.length > 0) {
    lines.push("- Evidence gaps:");
    for (const s of outcomes.evidence_gap_signals) {
      lines.push(
        `  - ${s.reason}: ${s.occurrences} occurrence(s) — children: ${s.child_ids.join(", ") || "none"}`,
      );
    }
  }

  if (outcomes.state_repair_signals.length > 0) {
    lines.push("- State repair / runtime review signals:");
    for (const s of outcomes.state_repair_signals) {
      lines.push(
        `  - ${s.signal} (${s.reason}): ${s.occurrences} occurrence(s) — children: ${s.child_ids.join(", ") || "none"}`,
      );
    }
  }

  if (lines.length === 0) {
    return "**Routing review:** No routing anomalies detected.";
  }

  return `**Routing review:**\n${lines.join("\n")}`;
}

function renderProviderRouting(
  summary?: ProviderRoutingSummary,
  outcomes?: RouterOutcomesSummary,
): string {
  const lines: string[] = ["### Provider routing"];

  if (summary) {
    lines.push(`- **Selected provider:** ${summary.selected_provider ?? "—"}`);
    lines.push(`- **Adapter:** ${summary.selected_adapter ?? "—"}`);
    lines.push(`- **Selection reason:** ${summary.selection_reason ?? "—"}`);
    lines.push(`- **Mode:** ${inferRoutingMode(summary)}`);
    if (summary.effective_policy_order && summary.effective_policy_order.length > 0) {
      lines.push(`- **Policy order:** ${summary.effective_policy_order.join(", ")}`);
    }
    if (typeof summary.registry_present === "boolean") {
      lines.push(`- **Registry present:** ${summary.registry_present ? "yes" : "no"}`);
    }
    if (typeof summary.fallback_eligible === "boolean") {
      lines.push(`- **Fallback eligible:** ${summary.fallback_eligible ? "yes" : "no"}`);
    }
  } else {
    lines.push("_No routing summary available._");
  }

  if (outcomes) {
    lines.push("");
    lines.push(renderRoutingReview(outcomes));
  }

  return lines.join("\n");
}

function hasAnomalyOrSummary(outcomes: RouterOutcomesSummary): boolean {
  return (
    outcomes.total_decisions > 0 ||
    outcomes.exhausted_decisions > 0 ||
    outcomes.fallback_attempts > 0 ||
    outcomes.recurring_failures.length > 0 ||
    outcomes.provider_monopoly_signals.length > 0 ||
    outcomes.evidence_gap_signals.length > 0 ||
    outcomes.state_repair_signals.length > 0
  );
}

export function buildPrBody(
  state: LoopState,
  branch: string,
  authoritativeChildCount?: number,
  routingSummary?: ProviderRoutingSummary,
  routerOutcomes?: RouterOutcomesSummary,
): string {
  const body: string[] = [
    `**Cluster ID:** ${state.cluster_id}`,
    `**Run ID:** ${state.run_id}`,
    `**Branch:** ${branch}`,
    `**Children completed:** ${authoritativeChildCount ?? state.completed_children.length}`,
    "",
  ];

  if (routingSummary || (routerOutcomes && hasAnomalyOrSummary(routerOutcomes))) {
    body.push(renderProviderRouting(routingSummary, routerOutcomes));
    body.push("");
  }

  body.push("_Generated by polaris finalize_");
  return body.join("\n");
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : undefined;
}

function findRoutingSummary(
  state: LoopState,
  telemetryEvents: unknown[],
): ProviderRoutingSummary | undefined {
  const childIds = Array.from(
    new Set([...state.completed_children, ...state.open_children]),
  );
  for (const childId of childIds) {
    const dispatchRecord = state.open_children_meta?.[childId]?.dispatch_record;
    if (dispatchRecord?.routing_summary) {
      return dispatchRecord.routing_summary;
    }
  }

  for (const event of telemetryEvents) {
    const rec = asRecord(event);
    if (!rec) continue;
    const routingSummary = rec["routing_summary"];
    if (routingSummary && typeof routingSummary === "object" && !Array.isArray(routingSummary)) {
      return routingSummary as ProviderRoutingSummary;
    }
  }

  return undefined;
}

function computeRoutingSummary(
  state: LoopState,
  repoRoot: string,
): { routingSummary?: ProviderRoutingSummary; routerOutcomes: RouterOutcomesSummary } {
  const telemetryFile = resolveTelemetryFilePath(state, repoRoot);
  const telemetryEvents = readJsonLines(telemetryFile);

  const artifacts: RunArtifacts = {
    runId: state.run_id,
    runDir: null,
    clusterDir: null,
    currentState: state,
    ledgerEvents: [],
    resultPackets: [],
    workerResultContracts: [],
    telemetryEvents,
    qcResults: [],
    clusterState: null,
  };

  const routerOutcomes = summarizeRouterOutcomes(artifacts);
  const routingSummary = findRoutingSummary(state, telemetryEvents);
  return { routingSummary, routerOutcomes };
}

export function createDraftPr(options: CreatePrOptions): string {
  const { repoRoot, branch, state, draft, authoritativeChildCount } = options;

  if (!state.cluster_id) {
    throw new Error(
      `createDraftPr: state.cluster_id is empty — cannot create PR without a cluster identifier`,
    );
  }

  const clusterSlug = state.cluster_id.toLowerCase().replace(/[^a-z0-9]/g, "-");
  const branchNorm = branch.toLowerCase().replace(/[^a-z0-9]/g, "-");
  // Boundary-aware: clusterSlug must match as a full token (surrounded by start/end or hyphens)
  const slugPattern = new RegExp(
    `(^|-)${clusterSlug.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(-|$)`,
  );
  if (!slugPattern.test(branchNorm)) {
    throw new Error(
      `createDraftPr: branch "${branch}" does not contain cluster ID slug "${clusterSlug}" — ` +
        `branch/cluster mismatch, aborting PR creation`,
    );
  }

  let routingSummary = options.routingSummary;
  let routerOutcomes = options.routerOutcomes;
  if (routingSummary === undefined || routerOutcomes === undefined) {
    const computed = computeRoutingSummary(state, repoRoot);
    routingSummary ??= computed.routingSummary;
    routerOutcomes ??= computed.routerOutcomes;
  }

  const title = `polaris finalize: ${state.cluster_id} (${state.run_id})`;
  const body = buildPrBody(
    state,
    branch,
    authoritativeChildCount,
    routingSummary,
    routerOutcomes,
  );

  const args = [
    "pr",
    "create",
    "--title",
    title,
    "--body",
    body,
    "--head",
    branch,
  ];
  if (draft) args.push("--draft");

  const output = execFileSync("gh", args, {
    cwd: repoRoot,
    encoding: "utf-8",
    stdio: ["pipe", "pipe", "inherit"],
  });

  return output.trim();
}
