import { execFileSync } from "node:child_process";
import type { LoopState } from "../loop/checkpoint.js";

export interface CreatePrOptions {
  repoRoot: string;
  branch: string;
  state: LoopState;
  draft: boolean;
}

export function createDraftPr(options: CreatePrOptions): string {
  const { repoRoot, branch, state, draft } = options;
  const title = `polaris finalize: ${state.run_id}`;
  const body = [
    `**Run ID:** ${state.run_id}`,
    `**Branch:** ${branch}`,
    `**Children completed:** ${state.completed_children.length}`,
    ``,
    `_Generated by polaris finalize_`,
  ].join("\n");

  const args = [
    "pr", "create",
    "--title", title,
    "--body", body,
    "--head", branch,
  ];
  if (draft) args.push("--draft");

  const output = execFileSync("gh", args, {
    cwd: repoRoot,
    encoding: "utf-8",
    stdio: ["pipe", "pipe", "inherit"],
  });

  return output.trim();
}
