import { execFileSync } from "node:child_process";
import type { LoopState } from "../loop/checkpoint.js";

export interface CreatePrOptions {
  repoRoot: string;
  branch: string;
  state: LoopState;
  draft: boolean;
}

/**
 * Create a GitHub pull request for a finalize run by invoking the `gh` CLI in the given repository.
 *
 * @param repoRoot - Filesystem path to use as the working directory for the `gh` command
 * @param branch - Name of the head branch for the pull request; must contain the normalized cluster slug
 * @param state - Loop state containing `cluster_id`, `run_id`, and `completed_children`; `cluster_id` must be present
 * @param draft - When true, create the pull request as a draft
 * @returns The stdout produced by the `gh` command, trimmed
 * @throws Error if `state.cluster_id` is empty
 * @throws Error if the provided `branch` (case-insensitive) does not include the cluster slug derived from `state.cluster_id`
 */
export function createDraftPr(options: CreatePrOptions): string {
  const { repoRoot, branch, state, draft } = options;

  if (!state.cluster_id) {
    throw new Error(
      `createDraftPr: state.cluster_id is empty — cannot create PR without a cluster identifier`
    );
  }

  const clusterSlug = state.cluster_id.toLowerCase().replace(/[^a-z0-9]/g, "-");
  if (!branch.toLowerCase().includes(clusterSlug)) {
    throw new Error(
      `createDraftPr: branch "${branch}" does not contain cluster ID slug "${clusterSlug}" — ` +
      `branch/cluster mismatch, aborting PR creation`
    );
  }

  const title = `polaris finalize: ${state.cluster_id} (${state.run_id})`;
  const body = [
    `**Cluster ID:** ${state.cluster_id}`,
    `**Run ID:** ${state.run_id}`,
    `**Branch:** ${branch}`,
    `**Children completed:** ${state.completed_children.length}`,
    ``,
    `_Generated by polaris finalize_`,
  ].join("\n");

  const args = [
    "pr", "create",
    "--title", title,
    "--body", body,
    "--head", branch,
  ];
  if (draft) args.push("--draft");

  const output = execFileSync("gh", args, {
    cwd: repoRoot,
    encoding: "utf-8",
    stdio: ["pipe", "pipe", "inherit"],
  });

  return output.trim();
}
